name: Fetch and Upload Atlas File

on:
  schedule:
    - cron: '0 7 */2 * *'
    - cron: '0 22 */2 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Atlas Release Info
        run: curl -o atlas.txt https://cdn.atlasclient.net/download/prod/latest/release-info

      - name: Commit and Push Update
        if: steps.changes.outcome != 'success'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add atlas.txt
          git commit -m "Update atlas.txt" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
